[package]
name = "syslog-agent-dtls-openssl"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["vendored"]
vendored = ["openssl/vendored"]

[dependencies]
syslog-agent-core.workspace = true
openssl.workspace = true
openssl-sys = "0.9"
foreign-types = "0.3"
socket2 = "0.6"
zeroize = "1"

